"""Add PasswordResetCode, Brand model and Product fields

Revision ID: 18c87ddace32
Revises: 5cb877a2fbf7
Create Date: 2025-11-15 00:57:08.045980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c87ddace32'
down_revision = '5cb877a2fbf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаем таблицу brand (если не существует)
    from sqlalchemy import inspect
    conn = op.get_bind()
    inspector = inspect(conn)
    tables = inspector.get_table_names()
    
    if 'brand' not in tables:
        op.create_table('brand',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('slug', sa.String(length=120), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('slug')
        )
        op.create_index('idx_brand_name', 'brand', ['name'], unique=False)
        op.create_index('idx_brand_slug', 'brand', ['slug'], unique=False)
        op.create_index(op.f('ix_brand_name'), 'brand', ['name'], unique=False)
        op.create_index(op.f('ix_brand_slug'), 'brand', ['slug'], unique=False)
    
    # Создаем таблицу password_reset_code (если не существует)
    if 'password_reset_code' not in tables:
        op.create_table('password_reset_code',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(length=200), nullable=False),
        sa.Column('code', sa.String(length=6), nullable=False),
        sa.Column('expires_at', sa.DateTime(), nullable=False),
        sa.Column('used', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('idx_resetcode_email', 'password_reset_code', ['email'], unique=False)
        op.create_index('idx_resetcode_expires', 'password_reset_code', ['expires_at'], unique=False)
        op.create_index('idx_resetcode_used', 'password_reset_code', ['used'], unique=False)
        op.create_index(op.f('ix_password_reset_code_email'), 'password_reset_code', ['email'], unique=False)
        op.create_index(op.f('ix_password_reset_code_expires_at'), 'password_reset_code', ['expires_at'], unique=False)
        op.create_index(op.f('ix_password_reset_code_used'), 'password_reset_code', ['used'], unique=False)
    
    # Обновляем таблицу product - добавляем колонки, если их нет
    product_cols = [col['name'] for col in inspector.get_columns('product')]
    
    with op.batch_alter_table('product', schema=None) as batch_op:
        if 'images' not in product_cols:
            batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))
        if 'specifications' not in product_cols:
            batch_op.add_column(sa.Column('specifications', sa.Text(), nullable=True))
        if 'rating' not in product_cols:
            batch_op.add_column(sa.Column('rating', sa.Float(), nullable=True))
        if 'reviews_count' not in product_cols:
            batch_op.add_column(sa.Column('reviews_count', sa.Integer(), nullable=True))
        if 'brand_id' not in product_cols:
            batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        
        # Создаем индексы и внешний ключ, если brand_id был добавлен
        if 'brand_id' not in product_cols:
            batch_op.create_index('idx_product_brand', ['brand_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_product_brand_id'), ['brand_id'], unique=False)
            batch_op.create_foreign_key('fk_product_brand_id', 'brand', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_brand_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_product_brand_id'))
        batch_op.drop_index('idx_product_brand')
        batch_op.drop_column('brand_id')
        batch_op.drop_column('reviews_count')
        batch_op.drop_column('rating')
        batch_op.drop_column('specifications')
        batch_op.drop_column('images')
    
    # Удаляем таблицы
    op.drop_index(op.f('ix_password_reset_code_used'), table_name='password_reset_code')
    op.drop_index(op.f('ix_password_reset_code_expires_at'), table_name='password_reset_code')
    op.drop_index(op.f('ix_password_reset_code_email'), table_name='password_reset_code')
    op.drop_index('idx_resetcode_used', table_name='password_reset_code')
    op.drop_index('idx_resetcode_expires', table_name='password_reset_code')
    op.drop_index('idx_resetcode_email', table_name='password_reset_code')
    op.drop_table('password_reset_code')
    
    op.drop_index(op.f('ix_brand_slug'), table_name='brand')
    op.drop_index(op.f('ix_brand_name'), table_name='brand')
    op.drop_index('idx_brand_slug', table_name='brand')
    op.drop_index('idx_brand_name', table_name='brand')
    op.drop_table('brand')

    # ### end Alembic commands ###
