"""Initial migration with indexes and OrderHistory

Revision ID: 5cb877a2fbf7
Revises: 
Create Date: 2025-11-14 23:56:22.739232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cb877a2fbf7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_index('idx_category_name', ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_category_name'), ['name'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=120), nullable=False),
    sa.Column('last_name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('password_hash', sa.String(length=200), nullable=False),
    sa.Column('avatar', sa.String(length=300), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('idx_user_email', ['email'], unique=False)
        batch_op.create_index('idx_user_role', ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    op.create_table('work',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('link', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.create_index('idx_work_created', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_work_title'), ['title'], unique=False)

    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.create_index('idx_order_created', ['created_at'], unique=False)
        batch_op.create_index('idx_order_status', ['status'], unique=False)
        batch_op.create_index('idx_order_user', ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_user_id'), ['user_id'], unique=False)

    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=300), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index('idx_product_category', ['category_id'], unique=False)
        batch_op.create_index('idx_product_price', ['price'], unique=False)
        batch_op.create_index('idx_product_stock', ['stock'], unique=False)
        batch_op.create_index('idx_product_title', ['title'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_price'), ['price'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_stock'), ['stock'], unique=False)
        batch_op.create_index(batch_op.f('ix_product_title'), ['title'], unique=False)

    op.create_table('order_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('changed_by', sa.String(length=200), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.create_index('idx_orderhistory_created', ['created_at'], unique=False)
        batch_op.create_index('idx_orderhistory_order', ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_history_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_history_order_id'), ['order_id'], unique=False)

    op.create_table('order_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['order.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.create_index('idx_orderitem_order', ['order_id'], unique=False)
        batch_op.create_index('idx_orderitem_product', ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_order_item_product_id'), ['product_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_item_product_id'))
        batch_op.drop_index(batch_op.f('ix_order_item_order_id'))
        batch_op.drop_index('idx_orderitem_product')
        batch_op.drop_index('idx_orderitem_order')

    op.drop_table('order_item')
    with op.batch_alter_table('order_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_history_order_id'))
        batch_op.drop_index(batch_op.f('ix_order_history_created_at'))
        batch_op.drop_index('idx_orderhistory_order')
        batch_op.drop_index('idx_orderhistory_created')

    op.drop_table('order_history')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_title'))
        batch_op.drop_index(batch_op.f('ix_product_stock'))
        batch_op.drop_index(batch_op.f('ix_product_price'))
        batch_op.drop_index(batch_op.f('ix_product_created_at'))
        batch_op.drop_index(batch_op.f('ix_product_category_id'))
        batch_op.drop_index('idx_product_title')
        batch_op.drop_index('idx_product_stock')
        batch_op.drop_index('idx_product_price')
        batch_op.drop_index('idx_product_category')

    op.drop_table('product')
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_order_user_id'))
        batch_op.drop_index(batch_op.f('ix_order_status'))
        batch_op.drop_index(batch_op.f('ix_order_created_at'))
        batch_op.drop_index('idx_order_user')
        batch_op.drop_index('idx_order_status')
        batch_op.drop_index('idx_order_created')

    op.drop_table('order')
    with op.batch_alter_table('work', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_title'))
        batch_op.drop_index(batch_op.f('ix_work_created_at'))
        batch_op.drop_index('idx_work_created')

    op.drop_table('work')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_last_name'))
        batch_op.drop_index(batch_op.f('ix_user_first_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_created_at'))
        batch_op.drop_index('idx_user_role')
        batch_op.drop_index('idx_user_email')

    op.drop_table('user')
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_category_name'))
        batch_op.drop_index('idx_category_name')

    op.drop_table('category')
    # ### end Alembic commands ###
